server:
  port: 8011

spring:
  elasticsearch:
    rest:
      connection-timeout: 120s
      read-timeout: 120s
  data:
    elasticsearch:
      repositories:
        enabled: true
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework: INFO
    com:
      mayank:
        learning:
          elasticsearch: INFO
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/elasticsearch-project.log